### ISSUE TITLE
No rule to make targe 'list.o' 

### ISSUE THREAD

**Issue by Tierney0115** [bonnyfone/adb-arm#2]

**Comment by Tierney0115** [comment]
I am building adb 1.0.32 by using android 5.0.1 r01 branch. The source code is different. How can I know which .c file I need to include it into makefile. Thanks.

**Comment by bonnyfone** [comment]
Hi! 
I never tried to build 1.0.32 but I know that something is changed. I suggest you to visit this post on StackOverflow: http://stackoverflow.com/questions/5904765/build-android-adb-for-arm-processor/31786368#31786368

An user (zgoda) commented on my post and he said that he was able to build 1.0.32. You may try to contact him or ask for clarification.
