### ISSUE TITLE
Can you compile a new one ?

### ISSUE THREAD

**Issue by andrewleo** [bonnyfone/adb-arm#5]
ADB from 1.0.36 come with some new features, such as reconnect, it is very important to keep multi devices stablely, so can you build a new one, or can you introduce the build steps?

**Comment by nikolakoco89** [comment]
I am also in need for adb 1.0.36, were you successful into building one?

**Comment by andrewleo** [comment]
adb for arm( version 1.0.37): https://www.androidfilehost.com/?fid=312978532265361625

By the way, maybe you can star this repository: https://github.com/hduong85/arm_adb, and compile arm adb yourself.

**Comment by andrewleo** [comment]
1.0.36 here: https://www.androidfilehost.com/?fid=673368273298924834

**Comment by nikolakoco89** [comment]
Thank you very much :)
